reroll:
  item:
    ==: org.bukkit.inventory.ItemStack #this must be here, don't remove it.
    type: DIAMOND_BLOCK
    amount: 1
  isEnabled: true
  eachHeroRequiresPermissions: false
  cooldown: 1
powerOnStart:
  isEnabled: true
